---
# defaults file for user-mysql
# Users
# Format:
# user_profiles:
#   - initials: mho
#     sudo_password: password
#     mysql_password: password
#     ssh_key: <SSHKEY>
#     devops: 0
#     mysqlRW: 0
#     sudo: 0
#     hostgroup: 1
#     active: 1
#     state: present
#   - initials: mho
#     upassword: password
#     ssh_key: <SSHKEY>
#     state: present
#   - initials: mho
#     state: absent
#     remove: false
#   - initials: mho
#     state: absent
#     remove: true
user_profiles: []

# service_users:
#   - username:     service_name
#     password:     *somebighashhere
#     database:     IAPTus_Service1
#     allowedhost:  10.3.200.%
#     hostgroup:    1
service_users: []
