---
- name: Converge
  hosts: all
  vars:
    lvm_group:
      - physical_devices: '/dev/sdb'
        lvm_group_name: 'vg_data'
        lvm_physical_devices: '/dev/sdb1'
        lvm_logical_volume_name: 'lv_data'
        lvm_mount_point: '/mnt/data'
  tasks:
    - name: "Include lvm"
      include_role:
        name: "lvm"
