---
# vars file for user-mysql
privs:
  - SELECT
  - INSERT
  - UPDATE
  - DELETE
  - CREATE
  - DROP
  - PROCESS
  - REFERENCES
  - INDEX
  - ALTER
  - SHOW DATABASES
  - CREATE TEMPORARY TABLES
  - LOCK TABLES
  - EXECUTE
  - CREATE VIEW
  - SHOW VIEW
  - CREATE ROUTINE
  - ALTER ROUTINE
  - TRIGGER
