---
# defaults file for nagios
nagios_ver: 4.5.5
nagios_plugins_ver: 2.4.12
nagiostv_version: 0.9.2

nagios_debs:
  - gcc
  - make
  - unzip
  - libgd3
  - libgd-dev
  - libssl-dev
  - fcgiwrap
  - apache2-utils
  - python3-setuptools
  - python3-pip
  - libmariadb-dev-compat
  - python3-passlib
  - autoconf
  - automake
  - gcc
  - libc6
  - libmcrypt-dev
  - make
  - libssl-dev
  - wget
  - bc
  - gawk
  - dc
  - build-essential
  - snmp
  - libnet-snmp-perl
  - gettext
